trigger:
- 1.1.1

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    cd ui
    yarn config set registry "https://registry.npm.taobao.org"
    yarn install
    yarn build --mode cdn
  displayName: 'yarn build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Hello world，$name"